language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: rake test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1dd9a22740abde064103
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
